version: '3.8'

services:
  flaskapp:
    container_name: testtaskflask_app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env_file
    volumes:
      - ./app:/home/python/app
    # command: bash -c "flask db init && flask db migrate && flask db upgrade"
    command: >
      bash -c  "pip install importlib_metadata 
      && flask db init
      && flask db migrate
      && flask db upgrade"
    links:
      - flaskdb
    depends_on:
      - flaskdb
    ports:
      - 5000:5000
    networks:
      - testtaskflask-api


  flaskdb:
    container_name: testtaskflask_db
    env_file:
      - .env_psql
    image: postgres:latest
    restart: "on-failure"
    ports:
      - 5432:5432
    networks:
      - testtaskflask-api
    volumes:
      - pg_data_volume:/var/lib/postgresql/data


networks:
  testtaskflask-api:

volumes:
  pg_data_volume:
